name: farmacia_desk_web
description: Web app farmacia gestione ricette e assistiti
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.30.0
  cloud_firestore: ^4.17.0
  file_picker: ^8.0.0+1
  http: ^1.2.2
  google_sign_in: 6.3.0
  syncfusion_flutter_pdf: ^29.1.41
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
